version: '3.8'
services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db  # Match the MySQL container name
      DB_PORT: 3306      # Internal MySQL port
      DB_DATABASE: ba
      DB_USERNAME: root
      DB_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: db
    ports:
      - 3307:3306  # Only needed if you want external access
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ba
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 5s
      timeout: 10s
      retries: 30

volumes:
  dbdata: